// Customer fetching
export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS';
export const CUSTOMER_FETCH_FAILED = 'CUSTOMER_FETCH_FAILED';

// Customer deletion
export const CUSTOMER_DELETION_SUCCESS = 'CUSTOMER_DELETION_SUCCESS';
export const CUSTOMER_DELETION_FAILED = 'CUSTOMER_DELETION_FAILED';

// Customer creation
export const CUSTOMER_CREATION_SUCCESS = 'CUSTOMER_CREATION_SUCCESS';
export const CUSTOMER_CREATION_FAILED = 'CUSTOMER_CREATION_FAILED';

// Customer update
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED';
