export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';