// Admin authentification
export const ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS';
export const ADMIN_AUTH_FAILED = 'ADMIN_AUTH_FAILED';

// User fetching
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

// Customer fetching
export const CUSTOMERS_FETCH_SUCCESS = 'CUSTOMERS_FETCH_SUCCESS';
export const CUSTOMERS_FETCH_FAILED = 'CUSTOMERS_FETCH_FAILED';

// Individual customer fetching
export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS';
export const CUSTOMER_FETCH_FAILURE = 'CUSTOMER_FETCH_FAILURE';

// Customer deletion
export const CUSTOMER_DELETION_SUCCESS = 'CUSTOMER_DELETION_SUCCESS';
export const CUSTOMER_DELETION_FAILED = 'CUSTOMER_DELETION_FAILED';

// Customer creation
export const CUSTOMER_CREATION_SUCCESS = 'CUSTOMER_CREATION_SUCCESS';
export const CUSTOMER_CREATION_FAILED = 'CUSTOMER_CREATION_FAILED';

// Customer update
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED';

// Products fetching
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';

// Products fetching with pagination
export const PRODUCT_FETCH_WITH_PAGINATION_SUCCESS = 'PRODUCT_FETCH_WITH_PAGINATION_SUCCESS';

// Product deletion
export const PRODUCT_DELETION_SUCCESS = 'PRODUCT_DELETION_SUCCESS';
export const PRODUCT_DELETION_FAILURE = 'PRODUCT_DELETION_FAILURE';

// Product creation
export const PRODUCT_CREATION_SUCCESS = 'PRODUCT_CREATION_SUCCESS';
export const PRODUCT_CREATION_FAILURE = 'PRODUCT_CREATION_FAILURE';

// Product update
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE';


// Orders fetching
export const ORDER_FETCH_SUCCESS ='ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILURE ='ORDER_FETCH_FAILURE';

// Order deletion
export const ORDER_DELETION_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_DELETION_FAILURE = 'ORDER_UPDATE_FAILURE';